uploading test results as artifacts

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,9 +17,19 @@ jobs:
       - name: Test-Runner Script
         run: |
           ./test-runner.sh
-          # Check the exit status of the tests and fail the workflow if they fail
-          if [ $? -ne 0 ]; then
-            echo "Tests failed. Failing the workflow."
-            exit 1
-          fi
-      - run: echo "This job's status is ${{ job.status }}."
+          # # Check the exit status of the tests and fail the workflow if they fail
+          # if [ $? -ne 0 ]; then
+          #   echo "Tests failed. Failing the workflow."
+          #   exit 1
+          # fi
+
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v2
+        with:
+          name: test-results
+          path: build/test/Testing/Temporary
+
+      - name: Display test logs
+        if: failure()
+        run: cat build/test/Testing/Temporary/LastTest.log
